<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="1" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38690" started-at="2020-04-17T01:54:33 COT" finished-at="2020-04-17T01:55:11 COT">
    <groups>
    </groups>
    <test name="TestMobileAppium" duration-ms="38690" started-at="2020-04-17T01:54:33 COT" finished-at="2020-04-17T01:55:11 COT">
      <class name="testinguy.appium.main.mainTest2">
        <test-method status="PASS" signature="inicioClase()[pri:0, instance:testinguy.appium.main.mainTest2@78aab498]" name="inicioClase" is-config="true" duration-ms="13003" started-at="2020-04-17T01:54:33 COT" finished-at="2020-04-17T01:54:46 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicioClase -->
        <test-method status="PASS" signature="IniciarSesion(java.lang.String, java.lang.String)[pri:0, instance:testinguy.appium.main.mainTest2@78aab498]" name="IniciarSesion" duration-ms="5878" started-at="2020-04-17T01:54:46 COT" description="Login" finished-at="2020-04-17T01:54:52 COT">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IniciarSesion -->
        <test-method status="PASS" signature="Test_Slider()[pri:0, instance:testinguy.appium.main.mainTest2@78aab498]" name="Test_Slider" duration-ms="10542" started-at="2020-04-17T01:54:52 COT" description="Ejercicio de presionar y soltar" finished-at="2020-04-17T01:55:02 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Slider -->
        <test-method status="FAIL" signature="Test_DragAndDrop()[pri:0, instance:testinguy.appium.main.mainTest2@78aab498]" name="Test_DragAndDrop" duration-ms="9174" started-at="2020-04-17T01:55:02 COT" description="Ejercicio de presionar, arrastrar y soltar" finished-at="2020-04-17T01:55:11 COT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Circle droppedxD] but found [Circle dropped]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Circle droppedxD] but found [Circle dropped]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testinguy.appium.main.mainTest2.Test_DragAndDrop(mainTest2.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_DragAndDrop -->
        <test-method status="SKIP" signature="testCaseSkipException()[pri:0, instance:testinguy.appium.main.mainTest2@78aab498]" name="testCaseSkipException" duration-ms="0" started-at="2020-04-17T01:55:11 COT" depends-on-methods="testinguy.appium.main.mainTest2.Test_DragAndDrop" finished-at="2020-04-17T01:55:11 COT">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method mainTest2.testCaseSkipException()[pri:0, instance:testinguy.appium.main.mainTest2@78aab498] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method mainTest2.testCaseSkipException()[pri:0, instance:testinguy.appium.main.mainTest2@78aab498] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseSkipException -->
      </class> <!-- testinguy.appium.main.mainTest2 -->
    </test> <!-- TestMobileAppium -->
  </suite> <!-- Suite -->
</testng-results>
